language: ruby

before_install:
  - gem install bundler

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

script: bundle exec rspec spec

cache: bundler
